# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-17 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='types',
            field=models.CharField(choices=[('Client', 'Client'), ('Employee', 'Employee'), ('LP', 'LP')], max_length=10),
        ),
    ]
