# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200317_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
