# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-13 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team')),
                ('description', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('position', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('order_id', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact_us.OfficeLocation')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
