# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-13 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'founders',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=500, null=True)),
                ('news_link', models.URLField(blank=True, null=True)),
                ('display_order_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['display_order_id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('company_subhead', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('invested_year', models.DateField(blank=True, null=True)),
                ('sectors', models.TextField(blank=True, null=True)),
                ('company_website_link', models.URLField(blank=True, null=True)),
                ('portfolio_detail_page_image', models.ImageField(blank=True, null=True, upload_to='background')),
                ('portfolio_background_image', models.ImageField(blank=True, null=True, upload_to='background')),
                ('company_logo', models.FileField(blank=True, help_text='upload .svg images', null=True, upload_to='background')),
                ('show_on_profile', models.BooleanField(default=True)),
                ('past_investment', models.BooleanField(default=False)),
                ('display_order_id_portfolio_page', models.IntegerField(null=True)),
                ('display_order_id_index_page', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_company.Category')),
            ],
            options={
                'verbose_name_plural': 'PortfolioCompanies',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_company.PortfolioCompany'),
        ),
        migrations.AddField(
            model_name='founders',
            name='port_folio_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_company.PortfolioCompany'),
        ),
    ]
