# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-24 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order_id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
