# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-24 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founders',
            name='founder_linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
