# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-24 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_company', '0002_founders_founder_linkedin_url'),
        ('portfolio_company', '0002_auto_20200324_1301'),
    ]

    operations = [
    ]
