# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_company', '0003_merge_20200324_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocompany',
            name='company_logo_in_white',
            field=models.FileField(blank=True, help_text='upload .svg images', null=True, upload_to='background'),
        ),
        migrations.AddField(
            model_name='portfoliocompany',
            name='show_on_index_page',
            field=models.BooleanField(default=True),
        ),
    ]
