# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-26 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_company', '0004_auto_20200326_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliocompany',
            old_name='show_on_index_page',
            new_name='show_in_recent_investment',
        ),
        migrations.RenameField(
            model_name='portfoliocompany',
            old_name='show_on_profile',
            new_name='show_on_portfolio_page',
        ),
    ]
