# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-02 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_company', '0005_auto_20200326_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliocompany',
            options={'verbose_name_plural': 'Portfolio Companies'},
        ),
    ]
