# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassociation',
            name='current_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacts',
            name='Note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
