# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-23 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0002_auto_20200423_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyassociation',
            name='current_company',
        ),
        migrations.AddField(
            model_name='contacts',
            name='present_company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
