# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-14 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcontact', '0003_auto_20200423_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='phone_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
