version: '3'

volumes:
  traefik_acme: {}
  rabbitmq_data: {}
  postgres_data: {}

services:


  postgres:
    env_file: .env
    restart: always
    image: postgres:latest
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  worker: &worker
    env_file: .env
    restart: always
    build: ../pravega
    command: python manage.py runserver 0.0.0.0:${BACKEND_PORT}
    links:
      - postgres:postgres

  backend:
    <<: *worker
    command: python manage.py runserver 0.0.0.0:${BACKEND_PORT}
    expose:
      - ${BACKEND_PORT}
    labels:
      - traefik.enable=true
      - traefik.backend.domain=${BACKEND_DOMAIN}
      - traefik.frontend.rule=Host:${BACKEND_DOMAIN}


  traefik:
    env_file: .env
    build: traefik
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_acme:/etc/traefik/acme/ # Defined in traefik/traefik.toml
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
